import argparse
import json
import sqlite3
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler


def load_reports(database_path: str) -> pd.DataFrame:
    if not Path(database_path).exists():
        raise FileNotFoundError(f"SQLite database not found: {database_path}")

    query = """
        SELECT
            id,
            analyzed_at,
            sample_name,
            machine_type,
            number_of_sections,
            imported_functions_count,
            threat_score,
            risk_level,
            suspicious_indicators_json
        FROM analysis_reports
        ORDER BY analyzed_at ASC
    """

    with sqlite3.connect(database_path) as connection:
        dataframe = pd.read_sql_query(query, connection)

    if dataframe.empty:
        raise ValueError("No analysis data found in analytics.db")

    dataframe["indicator_count"] = dataframe["suspicious_indicators_json"].apply(parse_indicator_count)
    dataframe["risk_level_numeric"] = dataframe["risk_level"].map({
        "LOW": 1,
        "MEDIUM": 2,
        "HIGH": 3,
        "CRITICAL": 4
    }).fillna(0)
    return dataframe


def parse_indicator_count(raw_value: str) -> int:
    try:
        parsed = json.loads(raw_value) if raw_value else []
        return len(parsed) if isinstance(parsed, list) else 0
    except json.JSONDecodeError:
        return 0


def classify_anomalies(dataframe: pd.DataFrame) -> pd.DataFrame:
    feature_columns = [
        "number_of_sections",
        "imported_functions_count",
        "threat_score",
        "indicator_count",
        "risk_level_numeric",
    ]

    output = dataframe.copy()

    if len(output) < 5:
        output["anomaly_label"] = np.where(
            (output["threat_score"] >= 70) | (output["indicator_count"] >= 3),
            "ANOMALOUS",
            "NORMAL",
        )
        output["anomaly_score"] = output["threat_score"] / 100.0
        return output

    scaler = StandardScaler()
    scaled_features = scaler.fit_transform(output[feature_columns])

    contamination = min(0.25, max(0.05, 1.0 / len(output)))
    model = IsolationForest(
        n_estimators=200,
        contamination=contamination,
        random_state=42,
    )
    predictions = model.fit_predict(scaled_features)
    scores = model.decision_function(scaled_features)

    output["anomaly_label"] = np.where(predictions == -1, "ANOMALOUS", "NORMAL")
    output["anomaly_score"] = (-scores + scores.max()).round(6)
    return output


def build_power_bi_export(dataframe: pd.DataFrame) -> pd.DataFrame:
    export_df = dataframe.copy()
    export_df["recommended_action"] = np.select(
        [
            export_df["anomaly_label"].eq("ANOMALOUS") & export_df["threat_score"].ge(80),
            export_df["anomaly_label"].eq("ANOMALOUS") & export_df["threat_score"].ge(60),
            export_df["anomaly_label"].eq("ANOMALOUS"),
        ],
        [
            "Immediate containment and reverse-engineering triage",
            "Priority sandbox detonation and analyst review",
            "Escalate for deeper behavioral validation",
        ],
        default="Retain for baseline telemetry",
    )

    ordered_columns = [
        "id",
        "analyzed_at",
        "sample_name",
        "machine_type",
        "number_of_sections",
        "imported_functions_count",
        "indicator_count",
        "threat_score",
        "risk_level",
        "anomaly_label",
        "anomaly_score",
        "recommended_action",
    ]
    return export_df[ordered_columns]


def main() -> None:
    parser = argparse.ArgumentParser(description="Run anomaly detection on Aegis-BlackBox analytics data.")
    parser.add_argument("--db", default="analytics.db", help="Path to the SQLite database generated by Module 2.")
    parser.add_argument("--out", default="final_report.csv", help="Output CSV file for Power BI consumption.")
    args = parser.parse_args()

    reports_df = load_reports(args.db)
    classified_df = classify_anomalies(reports_df)
    export_df = build_power_bi_export(classified_df)
    export_df.to_csv(args.out, index=False)

    print(f"AI classification complete. CSV exported to {args.out}")


if __name__ == "__main__":
    main()
